#!/usr/bin/python2.7

import argparse
import os
import sys
import subprocess
import textwrap

def main():

    # Redefine the exception handling routine so that it does NOT
    # do a trace dump if the user types ^C while lsseq is running.
    #
    old_excepthook = sys.excepthook
    def new_hook(exceptionType, value, traceback):
        if exceptionType != KeyboardInterrupt and exceptionType != IOError:
            old_excepthook(exceptionType, value, traceback)
        else:
            pass
    sys.excepthook = new_hook

    p = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent('''\
            Print table of powers of 2 up to n of integers 2 up to m.
            '''),
        usage="%(prog)s [OPTION]... [FILE]...")

    p.add_argument("--version", action="version", version="0.100")
    p.add_argument("--power", "-n", action="store", type=int, dest="n",
        default=3, metavar="N",
	help="The highest power in the table will be N (default=3).")
    p.add_argument("--max", "-m", action="store", type=int, dest="m",
        default=20, metavar="M", help="Print the powers from 2 to M (default=20).")
    p.add_argument("--primes", action="store_true",
        dest="onlyPrimes", default=False,
        help="only print out powers of primes" )

    p.add_argument("files", metavar="FILE", nargs="*",
        help="file names")

    args = p.parse_args()

    if args.n < 2 :
        print >> sys.stderr, os.path.basename(sys.argv[0]) + \
            ": error: the maximum power must be greater than one."
        sys.exit(0)

    if args.m < 2 :
        print >> sys.stderr, os.path.basename(sys.argv[0]) + \
            ": error: The maximum integer M to calculate powers for must be greater than one."
        sys.exit(0)

    primes = [True]*(args.m+1)

    # Sieve of Eratosthenes
    #
    if args.onlyPrimes : 
	p = 2
	while p < (args.m / 2) :
	    i = 2
	    while p*i <= args.m :
		primes[p*i] = False
		i += 1
	    p += 1
	    while not primes[p] :
		p += 1

    outputLine = ""
    formatList = [0]
    n = 1
    while n <= args.n :
	format = "{:>,d}"
        s = format.format(pow(args.m, n))
	# print s
        formatList.append(len(s))
	format = "{:>"+ str(formatList[-1]) + ",d}"
	outputLine += format.format(n)
	if n == 1 :
	    outputLine += " | "
	else :
	    outputLine += "  "
        n += 1

    # print formatList 

    dividingLine = "-"*len(outputLine)
    s = list(dividingLine)
    s[3] = '+'
    print outputLine
    print "".join(s)

    m = 2
    while m <= args.m :
	format = "{:>"+ str(formatList[1]) + ",d}"
	outputLine = format.format(m) + " | "
        n = 2
        while n <= args.n :
	    format = "{:>"+ str(formatList[n]) + ",d}"
            outputLine += format.format(pow(m, n)) + "  "
            n += 1
	if primes[m] :
	    print outputLine
        m += 1

        
if __name__ == '__main__':
    main()
