#!/usr/bin/python2.7

import argparse
import os
import sys
import subprocess
import textwrap
import time
import random
from operator import itemgetter

def main():

    INT = 0
    EXP = 1
    POWER = 2
    SHUFFLE = 3
    ASK_FOR_ROOT = 4

    # Redefine the exception handling routine so that it does NOT
    # do a trace dump if the user types ^C while the command is running.
    #
    old_excepthook = sys.excepthook
    def new_hook(exceptionType, value, traceback):
        if exceptionType != KeyboardInterrupt and exceptionType != IOError:
            old_excepthook(exceptionType, value, traceback)
        else:
            pass
    sys.excepthook = new_hook

    p = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent('''\
            Quiz the user's memory on squares and cubes, 4th powers etc.
            '''),
        usage="%(prog)s [OPTION]...")

    p.add_argument("--version", action="version", version="0.100")
    p.add_argument("--power", "-n", action="store", type=int, dest="n",
        default=2, nargs='+',
	help="List powers to test user on, eg. squares are 2, cubes 3 etc. (default=2).")
    p.add_argument("--max", "-m", action="store", type=int, dest="m",
        default=31, metavar="M",
	help="Test the Nth power of the integers 2 to M (default=31).")
    p.add_argument("--primes", action="store_true",
        dest="onlyPrimes", default=False,
        help="only test the Nth power of primes" )
    p.add_argument("--limit", action="store", type=int, dest="maxDigits",
        default=-1, metavar="MAX",
	help="Limit testing powers to integers of length MAX-digits or less")

    args = p.parse_args()

    if type(args.n) == int :
        powerList = [ args.n ]
    else :
        powerList = args.n

    for i in powerList :
        if i < 2 :
            print >> sys.stderr, os.path.basename(sys.argv[0]) + \
                ": error: --power must be greater than or equal to two."
            sys.exit(1)

    if args.m < 2 :
        print >> sys.stderr, os.path.basename(sys.argv[0]) + \
            ": error: the range (--max) must be greater than or equal to two."
        sys.exit(1)

    if args.maxDigits == 0 :
        print >> sys.stderr, os.path.basename(sys.argv[0]) + \
            ": warning: max digits is 0, nothing to print."
        sys.exit(0)

    userAnswerStr = ""
    quizList = []
    for n in powerList :
        i = 2
        while i <= args.m :
            x = pow(i, n)
            quizList.append((i, n, x, random.random(), True))
            quizList.append((i, n, x, random.random(), False))
            i += 1

    quizList.sort(key=itemgetter(SHUFFLE))

    i = 0
    while i < len(quizList) :

	n = quizList[i][INT]
	exponent = quizList[i][EXP]
	nthPower = quizList[i][POWER]
	askForRoot = quizList[i][ASK_FOR_ROOT]
	if askForRoot :
	    correctAnswer = n
	else :
	    correctAnswer = nthPower

	print ""
	startTime = time.time()
	try :
	    if askForRoot :
		userAnswerStr = raw_input(str(nthPower) + '^(1/' + str(exponent) + ')? --> ')
	    else :
		userAnswerStr = raw_input(str(n) + '^' + str(exponent) + '? --> ')
	except EOFError :
	    print "" 
	    print ""
	    print "exit"
	    break
	endTime = time.time()
	print endTime - startTime

	if userAnswerStr == 'pass' :
	    i += 1
	    continue


	try :
	    userAnswer = int(userAnswerStr)
	except ValueError :
	    print "Value typed was not an integer"
	else :
	    if userAnswer == correctAnswer :
		print "Correct"
		i += 1
	    else :
		print "Incorrect"
		continue

	print ""
	try :
	    userAnswerStr = raw_input('[continue?] ')
	except EOFError :
	    print "" 
	    print ""
	    print "exit"
	    break

	if userAnswerStr in ('exit', 'quit') :
	    print ""
	    print "exit"
	    break

    exit(0)

    # Note: this "isPrime" array will be filled with True 
    # in the case that we want to display ALL the integers
    # from 2,m - sorry, it's a bit of a cheat to use this list
    # this way, but it makes for clean code.
    #
    isPrime = [True]*(args.m+1)

    # Sieve of Eratosthenes - skipped when wanting to list ALL numbers
    #
    if args.onlyPrimes : 
	p = 2
	while p < (args.m / 2) :
	    i = 2
	    while p*i <= args.m :
		isPrime[p*i] = False
		i += 1
	    p += 1
	    while not isPrime[p] :
		p += 1

    # Find the largest prime in table
    #
    if not args.onlyPrimes :
	maxM = args.m
    else :
	i = len(isPrime) - 1
	while not isPrime[i] : 
	    i -= 1
	maxM = i
    maxN = args.n

    # Calculate the length of the strings of the highest powers
    # to be printed out (for formatting purposes)
    #
    intFormat = "{:d}"
    if args.maxDigits > 0 :
	n = 2
	while n <= maxN :
	    if len(intFormat.format(pow(2,n))) > args.maxDigits :
		n -= 1
		break
	    n += 1

	m = 2
	while m <= maxM :
	    if len(intFormat.format(pow(m,2))) > args.maxDigits :
		m -= 1
		break
	    m += 1

	if n < maxN :
	    maxN = n
	if m < maxM :
	    maxM = m

    outputLine = ""
    formatList = [0]
    commaFormat = "{:>,d}"
    prettyMaxLen = 0
    if args.maxDigits > 0 :
	prettyMaxLen = len(commaFormat.format(int("9"*args.maxDigits)))
    n = 1
    while n <= maxN :
	x = pow(maxM, n)
	sPretty = commaFormat.format(x)
	sInt = intFormat.format(x)

	if args.maxDigits > 0 :
	    if len(sInt) <= args.maxDigits :
		formatList.append(len(sPretty))
	    else :
		formatList.append(prettyMaxLen)
	else :
	    formatList.append(len(sPretty))

	commaFormatPad = "{:>"+ str(formatList[-1]) + ",d}"
	outputLine += commaFormatPad.format(n)
	if n == 1 :
	    outputLine = outputLine.replace("1", " ")
	    outputLine += " | "
	else :
	    outputLine += "  "
	n += 1

    # Make the dividing line between list of powers 
    # and first row of powers of 2.
    #
    dividingLine = "-"*len(outputLine)
    s = list(dividingLine)
    s[formatList[1] + 1] = '+'

    # Print the powers to be displayed on first row
    # then the dividing line.
    #
    print outputLine
    print "".join(s)

    # Now calculate and print the powers
    #
    m = 2
    while m <= maxM :
	commaFormatPad = "{:>"+ str(formatList[1]) + ",d}"
	outputLine = commaFormatPad.format(m) + " | "
        n = 2
	if isPrime[m] :
	    while n <= maxN :
		x = pow(m, n)
		commaFormatPad = "{:>"+ str(formatList[n]) + ",d}"
		if args.maxDigits > 0 :
		    if len(intFormat.format(x)) <= args.maxDigits :
			outputLine += commaFormatPad.format(x) + "  "
		    else :
			break
		else :
		    outputLine += commaFormatPad.format(x) + "  "
		n += 1
	    print outputLine
        m += 1
        
if __name__ == '__main__':
    main()
